### ISSUE TITLE
ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by xinthose** [sindresorhus/emittery#105]
I am using [@1.0.0](https://github.com/sindresorhus/emittery/releases/tag/v1.0.0) with TypeScript and compile using `gulp`.  When I import emittery, I use:
```typescript
import Emittery from 'emittery';
```
But when gulp compiles the code, it produces:
```js
const emittery_1 = __importDefault(require("emittery"));
```
and running the code in node fails.  
I am using `compilerOptions.module` = `commonjs` in my `tsconfig.json`.  Should I not be doing this?  I get a lot of errors in my application elsewhere if I use `esnext`.  

Full Error
```log
C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\station\order.js:12
const emittery_1 = __importDefault(require("emittery"));
                                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\node_modules\emittery\index.js from C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\station\order.js not supported.
Instead change the require of index.js in C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\station\order.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\station\order.js:12:36)
    at Object.<anonymous> (C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\station\station.js:15:17)
    at Object.<anonymous> (C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\job.js:11:19)
    at Object.<anonymous> (C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\main.js:31:15)
    at Object.<anonymous> (C:\Users\ADunsmoor\Documents\GitHub\Portalogic\Portalogic-Data-Service\dist\app.js:4:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
